apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base/empty.yaml

helmCharts:
- name: app
  releaseName: app
  chartHome: ../../charts
  chartName: app
  valuesFile: values.yaml
