namespace: dev

frontend:
  replicas: 1
  image:
    repository: jamiekariuki/frontend
    tag: "latest"

backend:
  replicas: 1
  image:
    repository: jamiekariuki/blog
    tag: "latest"
  envFrom:
  - secretRef:
      name: backend-secrets-dev
