name: CI

on:
  push:
    branches: [ main ]
    paths:
      #    - 'frontend-react/**'
      #    - 'backend-django/**'

permissions:
  contents: write

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      frontend_changed: ${{ steps.filter.outputs.frontend }}
      backend_changed: ${{ steps.filter.outputs.backend }}
    steps:
    - uses: actions/checkout@v4
    - id: filter
      uses: dorny/paths-filter@v2
      with:
        filters: |
          frontend:
            - 'frontend-react/**'
          backend:
            - 'backend-django/**'

  debug-frontend:
    runs-on: ubuntu-latest
    steps:
    - name: Debug secrets
      run: |
        echo "AWS Key: ${#AWS_SECRET_ACCESS_KEY}"
      env:
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  frontend:
    needs: detect-changes
    if: needs.detect-changes.outputs.frontend_changed == 'false'
    uses: ./.github/workflows/main-ci.yaml
    with:
      service_name: "frontend"
      dockerfile: "frontend-react"
      runtime: "node"

  backend:
    needs: detect-changes
    if: needs.detect-changes.outputs.backend_changed == 'false'
    uses: ./.github/workflows/main-ci.yaml
    with:
      service_name: "backend"
      dockerfile: "backend-django"
      runtime: "python"
