name: Frontend CI

on:
  push:
    branches: [ main ]
    paths:
      #    - 'frontend-react/**'
      #    - 'backend-django/**'

permissions:
  contents: write

jobs:

  frontend:
    uses: ./.github/workflows/main-ci.yaml
    with:
      service_name: "frontend"
      dockerfile: "frontend-react"
      runtime: "node"
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      HELM_REPO_PAT: ${{ secrets.HELM_REPO_PAT }}
